# Generated by Django 5.0 on 2024-02-16 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('still_member', models.BooleanField(default=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('need_surgery', models.BooleanField()),
                ('appointment_type', models.CharField(choices=[('checkup', 'checkup'), ('surgery', 'surgery')], max_length=20)),
                ('upcoming', models.BooleanField()),
                ('notes', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=models.SET('deleted doctor'), to='medtrack.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('allergies_exist', models.BooleanField()),
                ('allergies', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('sub_plans', models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium')], max_length=10)),
                ('address', models.CharField(default='', max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_on', models.DateField(default=django.utils.timezone.now)),
                ('end_on', models.DateField(default=django.utils.timezone.now)),
                ('medicine_prescribed', models.CharField(max_length=100)),
                ('how_many', models.IntegerField()),
                ('time_between', models.FloatField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medtrack.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtrack.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtrack.patient'),
        ),
    ]
