# Generated by Django 5.0 on 2024-02-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtrack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='username',
            new_name='user_id',
        ),
    ]
