# Generated by Django 5.0 on 2024-01-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(),
        ),
    ]
