# Generated by Django 5.0 on 2024-02-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtrack', '0002_rename_username_patient_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
    ]
