# Generated by Django 5.0 on 2024-01-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtrack', '0003_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('checkup', 'checkup'), ('surgery', 'surgery')], max_length=20),
        ),
    ]
