# Generated by Django 5.0 on 2024-02-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtrack', '0004_rename_user_patient_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user_id',
            new_name='username',
        ),
    ]
